add remaining screens
mbnexttime/emkn pull request #3
Opened 2022-09-25 20:14 UTC by alexgrebenshchikov

Флоу с изменением пароля доделал, навигация готова.
Также сделал проверку заполненности полей и проверку перехода назад

2022-09-25 21:48 UTC, mbnexttime requested changes

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/auth/SignInFragment.kt
> +    lateinit var router: RouterImpl
тихо тихо, инжектим Router

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/auth/SignInFragment.kt
> +        binding.submitButton.isEnabled = !(email.isNullOrBlank() || password.isNullOrBlank())
пустой логин тоже нельзя

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/auth/SignUpFragment.kt
> +    lateinit var router: RouterImpl
Router

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/auth/SignInFragment.kt
>  class SignInFragment : Fragment() {
стоп, ничего не понимаю
у нас же логин по Login, Password, причем тут email?

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/auth/SignUpFragment.kt
> +        binding.signUpButton.isEnabled =
давай разрешим пустые имена фамилии, они особо не нужны

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/changepassword/ChangePasswordConfirmationFragment.kt
> +    lateinit var router: RouterImpl
Router

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/changepassword/ChangePasswordConfirmationFragment.kt
> +        setupLayout()
setupLayout выполняется в onViewCreated

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/changepassword/ChangePasswordConfirmationFragment.kt
> +        binding.codeEditText.onVerificationCodeFilledListener = { code ->
что то с неймингом полей не так. ```onVerificationCodeChangeListener``` ?

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/changepassword/ChangePasswordConfirmationFragment.kt
> +        AlertDialog.Builder(requireContext())
тут не надо алерт

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/changepassword/CommitChangePasswordFragment.kt
> +    lateinit var router: RouterImpl
Router

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/changepassword/CommitChangePasswordFragment.kt
> +        setupLayout()
в onViewCreated

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/changepassword/CommitChangePasswordFragment.kt
> +    private fun subscribeToFormFields() {
пустая строка нужна

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/changepassword/CommitChangePasswordFragment.kt
> +class CommitChangePasswordFragment : Fragment() {
снова не понимаю. Commit это же уже непосредственно ввод нового пароля, при чем тут  email?

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/changepassword/ForgotPasswordFragment.kt
> +    lateinit var router: RouterImpl
Router

2022-09-25 21:48 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/emailconfirmation/EmailConfirmationFragment.kt
> +    lateinit var router: RouterImpl
Router

2022-09-26 19:19 UTC, alexgrebenshchikov commented on app/src/main/java/com/mcs/emkn/ui/changepassword/ChangePasswordConfirmationFragment.kt
> +        AlertDialog.Builder(requireContext())
почему здесь не нужен алерт?

2022-09-26 19:21 UTC, alexgrebenshchikov commented on app/src/main/java/com/mcs/emkn/ui/auth/SignUpFragment.kt
> +        binding.signUpButton.isEnabled =
по моему будет плохо, если препод будет видеть в списке учеников людей без имени и/или фамилии

2022-09-28 18:15 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/auth/SignUpFragment.kt
> +        binding.signUpButton.isEnabled =
они туда все равно могут ввести что угодно

2022-09-28 18:16 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/changepassword/ChangePasswordConfirmationFragment.kt
> +        AlertDialog.Builder(requireContext())
нужно тогда текст другой. типа что человеку придется заново код отсылать на почту

2022-09-30 18:21 UTC, mbnexttime commented
хорошая работа!

2022-09-30 18:21 UTC, merged