Courses vm
mbnexttime/emkn pull request #9
Opened 2022-10-22 21:32 UTC by alexgrebenshchikov

2022-10-22 23:19 UTC, mbnexttime requested changes
логика в целом понятна, но:
1) нужно синкать не только сеть, но и поля. если ты попытаешься из разных потоков изменить мапу, это исключение (Dispatchers.IO - это много потоков)
2) нужно разнести это все по разным контроллерам и хелперам. Дебажить 500 строк нереально
3) не надо держать ничего в полях. нет ничего плохого чтобы всегда все грузить из дб, это очень быстро. и это избавит от необходимости их синхронизировать
4) нужно чуть чуть почистить код от вложенности, поформатировать. сейчас читать сложно
5) нужно синкануть работу с бд, сейчас мне кажется где то логика нарушается. нужна транзакционность. если почисить код, здесь будет гораздо легче
6) любая работа с моделью должна вестись на другом потоке, не на том котором вызвали функцию

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/core/State.kt
> +    val data: T?,
если уж совсем припрет, делай вместо T, sealed class, в котором два подтипа: ```Presented(data: T), NotPresented()```. Не надо делать здесь нулл на уровне типа

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/database/CoursesDao.kt
> +    fun getPeriods(): List<PeriodEntity>
заведи отдельно dao для профилей

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +        val idsNeededForUpdate: MutableList<Pair<Int, Boolean>> = mutableListOf()
это вызывается на мейне, не надо здесь в дб ничего писать

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +        val idsNeededForUpdate: MutableList<Pair<Int, Boolean>> = mutableListOf()
и у тебя рейс в periodsStorage

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +        if (periodsStorage == null)
почему? я буду вызывать оба метода вместе, во время загрузки курсов периодов не будет

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +        periodsStorage?.let { storage ->
не на мейне

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +            if (periodsStorage == null) {
ух бля, какие то тяжелые ифы и вложенные условия

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +    private suspend fun loadProfiles(profilesIds: List<Int>) {
этим должна заниматься моделкьа профилей,либо какой то отдельный загрузчик

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +            } catch (e: Throwable) {
не понял, что за дб еррор?

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +            try {
зачем?

2022-10-22 23:19 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +            try {
зачем?

2022-10-23 16:53 UTC, alexgrebenshchikov commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +        if (periodsStorage == null)
сейчас логика предполагает, что сначала грузится информация об отмеченных периодах из базы в loadPeriods
если сначала загрузятся курсы может получиться так, что список курсов не соответствует фильтру

2022-10-23 16:54 UTC, alexgrebenshchikov commented
Изменил диспетчер у корутин, теперь синхронизация не нужна
Вынес логику общения с базой и загрузку профилей в отдельный класс

2022-10-23 22:05 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +        if (periodsStorage == null)
бэк обещает, что если грузим вообще без фильтров, то они отдадут дефолтный текущий период

2022-11-12 16:02 UTC, mbnexttime approved these changes

2022-11-12 16:02 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/di/SingletonScopedModule.kt
> +    fun provideAuthDb(
не понял нейминг

2022-11-12 16:02 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +            _coursesFlow.emit(State(null, true))
как ты себе это представляешь? у нас ui будет мигать и сбрасывать все текущие курсы?

2022-11-12 16:02 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +            _coursesFlow.emit(State(null, true))
кидай текущие курсы и hasMore: true. нужно еще добавить отдельный флоу, по которому ты можешь кидать текущий период (можно в принципе передавать как dafault его у текущего flow)

2022-11-12 16:02 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +            localStorage.periodsStorage?.forEach { (id, period) ->
не понимаю эту логику, можешь чуть раскрыть?

2022-11-12 16:02 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +            dbInteractor.updatePeriodsCheckedStateInDb(idsNeededForUpdate)
зачем здесь это делается? можно же по умолчанию просто значение задать в дб

2022-11-12 16:02 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +
что то здесь как то очень мудренно

2022-11-12 16:02 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +                (chosenIdsSet - (localStorage.coursesStorage?.keys ?: setOf()).toSet()).toList()
т.е если мы загрузили период то больше никогда за ним в сеть не пойдем?

2022-11-12 16:02 UTC, mbnexttime commented on app/src/main/java/com/mcs/emkn/ui/courses/viewmodels/CoursesViewModel.kt
> +        var coursesStorage: MutableMap<Int, List<CourseEntity>>? = null,
ненененененене выпиливай это

2022-11-12 16:03 UTC, merged